module.exports = {
  quizzes: [
    {
      id: 1,
      image: null,
      gif: null,
      question: "Who is the Pokemon Anime’s main character?",
      options: ["Misty", "Ash", "Light", "Gary"],
      answer: ["Ash", 2],
    },
    {
      id: 2,
      image: null,
      gif: null,
      question: "Sophie is a character from which anime movie?",
      options: [
        "Go! Princess PreCure",
        "Snow White With The Red Hair",
        "Howl's Moving Castle",
        "Sailor Moon",
      ],
      answer: ["Howl's Moving Castle", 3],
    },
    {
      id: 3,
      image: null,
      gif: null,
      question:
        "In Dragon Ball Super, Goku is sent to destroy earth. What happened to make him change his ways?",
      options: [
        "He just realised it was quite mean",
        "He bumped his head",
        "He couldn't be bothered in the end",
        "No-one knows",
      ],
      answer: ["He bumped his head", 2],
    },
    {
      id: 4,
      image: null,
      gif: null,
      question: "What do you have to do with Pokemon?",
      options: [
        "Snatch 'em all",
        "Fetch 'em all",
        "Catch 'em all",
        "Kill 'em all",
      ],
      answer: ["Catch 'em all", 3],
    },
    {
      id: 5,
      image: null,
      gif: null,
      question: "How do you do a Naruto run?",
      options: [
        "Put your head forward and arms back",
        "Put your left foot in, right foot out",
        "You do the hockey cokey and turn around",
        "None of the above",
      ],
      answer: ["Put your head forward and arms back", 1],
    },
    {
      id: 6,
      image:
        "https://www.beano.com/wp-content/uploads/legacy/54203_blob.png?w=769.984375&strip=all&quality=76",
      gif: null,
      question: "Who is this chubby baby from Spirited Away?",
      options: ["Buddy", "Boh", "Brian", "Beng"],
      answer: ["Boh", 2],
    },
    {
      id: 7,
      image: null,
      gif: null,
      question: "How do you spell anime in Japanese?",
      options: ["私の", "マンガ", "オタク", "アニメ"],
      answer: ["アニメ", 4],
    },
    {
      id: 8,
      image:
        "https://www.beano.com/wp-content/uploads/legacy/54207_blob.png?w=769.984375&strip=all&quality=76",
      gif: null,
      question: "Which famous anime movie is this from?",
      options: [
        "Spirited Away",
        "Howl's Moving Castle",
        "My Neighbour Totoro",
        "Kiki's Delivery Service",
      ],
      answer: ["My Neighbour Totoro", 3],
    },
    {
      id: 9,
      image: null,
      gif: null,
      question: "Which of these ISN'T a type of Pokemon?",
      options: ["Electric", "Rubber", "Grass", "Fire"],
      answer: ["Rubber", 2],
    },
    {
      id: 10,
      image: null,
      gif: null,
      question: "Fill in the blank...Dragon ___ Z",
      options: ["Ball", "Beach", "Film", "Mech"],
      answer: ["Ball", 1],
    },
    {
      id: 11,
      image: null,
      gif: null,
      question: "What kind of person is Naruto?",
      options: ["A samurai", "A knight", "A ninja", "A soldier"],
      answer: ["A ninja", 3],
    },
    {
      id: 12,
      image:
        "https://www.beano.com/wp-content/uploads/legacy/54212_Catbus.jpg?w=769.984375&strip=all&quality=76",
      gif: null,
      question: "In my Neighbour Totoro, what's unusual about this cat?",
      options: [
        "It likes water",
        "It's vegan",
        "It turns into a plane",
        "It's also a bus",
      ],
      answer: ["It's also a bus", 4],
    },
    {
      id: 13,
      image: null,
      gif: null,
      question: "In which anime series is Ash Ketchum the main character?",
      options: [
        "Eyeshield 21",
        "Pokémon",
        "Cowboy Bebop",
        "Super Dimension Fortress Macross",
      ],
      answer: ["Pokémon", 2],
    },
    {
      id: 14,
      image: null,
      gif: null,
      question: "Dragon Ball’ was created by whom in 1984?",
      options: [
        "Akira Toriyama",
        "Satoshi Tajiri",
        "Hirohiko Araki",
        "Hayao Miyazaki",
      ],
      answer: ["Akira Toriyama", 1],
    },
    {
      id: 15,
      image: null,
      gif: null,
      question: "What is the name of Studio Ghibli’s well-known mascot?",
      options: ["Kiki", "Bakura", "Ponyo", "Totoro"],
      answer: ["Totoro", 4],
    },
    {
      id: 16,
      image: null,
      gif: null,
      question: "In ‘Sailor Moon’ the anime character Makoto Kino transforms",
      options: [
        "Sailor Mercury",
        "Sailor Venus",
        "Sailor Jupiter",
        "Sailor Mars",
      ],
      answer: ["Sailor Jupiter", 3],
    },
    {
      id: 17,
      image: null,
      gif: null,
      question:
        "In ‘Nurato’, the main character, Naruto Uzumaki, is a host for the powerful Nine-Tales. What creature is the Nine-Tails?",
      options: ["Wolf", "Fox", "Bear", "Cat"],
      answer: ["Fox", 2],
    },
    {
      id: 18,
      image: null,
      gif: null,
      question:
        "Yubaba is a witch in which animated film written and directed by Hayao Miyazaki?",
      options: [
        "Spirited Away",
        "Castle in the Sky",
        "Ocean Waves",
        "Pom Poko",
      ],
      answer: ["Spirited Away", 1],
    },
    {
      id: 19,
      image: null,
      gif: null,
      question: "Which anime series is set in the world of Amestris?",
      options: ["Naruto", "Fullmetal Alchemist", "Sailor Moon", "Pokemon"],
      answer: ["Fullmetal Alchemist", 2],
    },
    {
      id: 20,
      image: null,
      gif: null,
      question:
        "In ‘Howl’s Moving Castle’, Sophie is transformed into an old woman by a witch. How old is Sophie as an old woman?",
      options: ["75 years old", "90 years old", "87 years old", "67 years old"],
      answer: ["90 years old", 2],
    },
    {
      id: 21,
      image: null,
      gif: null,
      question:
        "In ‘One Piece’, Monkey D. Luffy originally sets out with the Straw Hat Pirates to become the pirate king on which ship?",
      options: ["Going Merry", "Jolly Roger", "Thousand Sunny", "Ever Darker"],
      answer: ["Going Merry", 1],
    },
    {
      id: 22,
      image: null,
      gif: null,
      question:
        "Which planet is also known as the Dragon World in ‘Dragon Ball’?",
      options: ["Earth", "Mars", "Jupiter", "Neptune"],
      answer: ["Earth", 1],
    },
    {
      id: 23,
      image: null,
      gif: null,
      question:
        "Which series is set in the dark underworld of Victorian London?",
      options: [
        "Phantomhive",
        "Black Butler",
        "Valkyria Chronicles",
        "Blue Exorcist",
      ],
      answer: ["Black Butler", 2],
    },
    {
      id: 24,
      image: null,
      gif: null,
      question:
        "In which anime series are Chief Daisuke Aramaki and Major Motoko Kusanag two of the main characters?",
      options: [
        "Paranoia Agent",
        "Dominion",
        "Ghost in the Shell",
        "Fullmetal Alchemist",
      ],
      answer: ["Ghost in the Shell", 3],
    },
    {
      id: 25,
      image: null,
      gif: null,
      question: "Which sport is the focus of ‘Eyeshield 21’?",
      options: ["Baseball", "American Football", "Tennis", "Soccer"],
      answer: ["American Football", 2],
    },
    {
      id: 26,
      image: null,
      gif: null,
      question:
        "In ’Cowboy Bebop’ Ein is a genetically engineered dog with human levels of intelligence. Which breed of dog is Ein?",
      options: [
        "Great Dane",
        "Cavalier King Charles Spaniel",
        "Dachshund",
        "Pembrokeshire Welsh Corgi",
      ],
      answer: ["Pembrokeshire Welsh Corgi", 4],
    },
    {
      id: 27,
      image: null,
      gif: null,
      question: "Which one of the following series is about time travel?",
      options: ["Steins;Gate", "Darker than Black", "City Hunter", "Devilman"],
      answer: ["Devilman", 4],
    },
    {
      id: 28,
      image: null,
      gif: null,
      question:
        "A girl searches for magical objects to fulfill her wish, which is the anime?",
      options: ["One Piece", "Dragon Ball", "Fairy Tail", "Naruto"],
      answer: ["Dragon Ball", 2],
    },
    {
      id: 29,
      image: null,
      gif: null,
      question: "What kind of wizard is Lucy in “Fairy Tail” anime?",
      options: ["Ice Wizard", "Celestial Wizard", "Fire Wizard", "Sky Wizard"],
      answer: ["Celestial Wizard", 2],
    },
    {
      id: 30,
      image: null,
      gif: null,
      question:
        "Which of the following characters does the “Gum-Gum Pistol” attack belong to?",
      options: ["Chobits", "Black Butler", "Monkey D.Luffy", "Titan"],
      answer: ["Monkey D.Luffy", 3],
    },
    {
      id: 31,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/4Z2ZT6DEm_EORh_tUnAocLiemLxNE876EIejVQVq_AA-1-1024x591.jpg",
      gif: null,
      question:
        "Naruto has different types of modes. Do you know what is the name of this mode?",
      options: [
        "Kuruma Chakra Mode",
        "Six Paths Sage Mode",
        "Tailed Beast Bomb Rasen Shiruken",
        "None of the above",
      ],
      answer: ["Six Paths Sage Mode", 2],
    },
    {
      id: 32,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/9b580c3252099d75274ce67f638872db-1024x640.jpg",
      gif: null,
      question: "He is Light Yagami. He is the main character of ….. anime.",
      options: ["One Piece", "Fairy Tail", "Death Note", "Dragon Ball"],
      answer: ["Death Note", 3],
    },
    {
      id: 33,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/https-_s3-ap-northeast-1.amazonaws.com_psh-ex-ftnikkei-3937bb4_images_8_8_8_0_20780888-3-eng-GB_Cropped-15579467990511961-1024x576.jpg",
      gif: null,
      question: "What is the anime of this picture?",
      options: [
        "Spirited Away",
        "My Neighbour Totoro",
        "One Piece",
        "Fairy Tail",
      ],
      answer: ["Spirited Away", 1],
    },
    {
      id: 34,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/a2deecc48e8922fb89e2c473d0409193e2e478f6r1-1280-720v2_uhq-1024x576.jpg",
      gif: null,
      question: "Who is he?",
      options: ["Nami", "Usopp", "Rorona Zoro", "Nico Robin"],
      answer: ["Rorona Zoro", 3],
    },
    {
      id: 35,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/catbusbg_by_nellehfox_dcrfa07-fullview-1024x768.jpg",
      gif: null,
      question: "This cat is one of the cutest characters of …… anime.",
      options: ["SAO", "Naruto", "Spirited Away", "In My Neighbour Totoro"],
      answer: ["In My Neighbour Totoro", 4],
    },
    {
      id: 36,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/top-10-beautiful-cute-ghibli-girls-06-1024x611.jpg",
      gif: null,
      question: "Name this character",
      options: ["Nami", "Sophie", "Kiki", "Haruka"],
      answer: ["Sophie", 2],
    },
    {
      id: 37,
      image: null,
      gif: null,
      question:
        "What is the name of the ability that allows Fujinuma Satoru to time travel?",
      options: ["Revival", "Time Leap", "Return By Death", "Dues Ex"],
      answer: ["Revival", 1],
    },
    {
      id: 38,
      image: null,
      gif: null,
      question:
        'Which character (Kozu No Honkai) said "being wanted... just feels so good"?',
      options: [
        "Yasuraoka Hanabi",
        "Awaya Mugi",
        "Kanai Narumi",
        "Minagawa Akane",
      ],
      answer: ["Minagawa Akane", 4],
    },
    {
      id: 39,
      image: null,
      gif: null,
      question:
        '"The law doesn\'t protect people. People protect the law." From which anime is this quote from?',
      options: [
        "Gyakuten Saiban",
        "Inferno Cop",
        "Psycho-Pass",
        "Wizard Barristers",
      ],
      answer: ["Psycho-Pass", 3],
    },
    {
      id: 40,
      image: null,
      gif: null,
      question:
        "According to AnimeNewsNetwork (2015), how much does it cost, approximately, to produce 1 season/13 episodes of an anime?",
      options: [
        "$12 - 20 million",
        "$120000 - 200000",
        "$1200 - 20000",
        "$1.2 - 2 million",
      ],
      answer: ["$1.2 - 2 million", 4],
    },
    {
      id: 41,
      image: null,
      gif: null,
      question: "What is the name of Megumin's (Konosuba) pet or familiar?",
      options: ["Kuro", "Chomusuke", "Kuroneko", "Megusuke"],
      answer: ["Chomusuke", 2],
    },
    {
      id: 42,
      image: null,
      gif: null,
      question:
        'Which fast food chain advertised throughout the anime"Code Geass"',
      options: ["McDonald's", "Subway", "KFC", "Piza Hut"],
      answer: ["Pizza Hut", 4],
    },
    {
      id: 43,
      image: null,
      gif: null,
      question:
        'In a curry cooking competition, which character just heated a bag of pre-made curry... and ate it all herself? (From the anime"Kantai Collection")',
      options: ["Inazuma", "Fubuki", "Shimakaze", "Yuudachi"],
      answer: ["Shimakaze", 3],
    },
    {
      id: 44,
      image: null,
      gif: null,
      question: "How tall is Haruyuki Arita?",
      options: ["134 cm", "139 cm", "145 cm", "149 cm"],
      answer: ["139 cm", 2],
    },
    {
      id: 45,
      image: null,
      gif: null,
      question:
        "Which country did Nakiri Alice live in, prior to joining Totsuki?",
      options: ["Sweden", "France", "Denmark", "Finland"],
      answer: ["Denmark", 3],
    },
    {
      id: 46,
      image: null,
      gif: null,
      question:
        'Which anime has a character called:\n"Jugem-Jugem Poop Throwing Machine Shin-chan\'s Day Before Yesterday Underwear Shin-chan•s Life Balmunk Fezarion Isaac Schneider One Thirds Pure Feeling Two Thirds Worried-Over-A-HangnaiI Feeling Though Betrayal Knows My Name Or Does It? I Know The Unknown The Cuttlefish Tastes Kind Of Different Than It Did Last Time [...] Pepepepepepepepepepepe Runny Diarrhea"?',
      options: [
        "Crayon Shin-Chan",
        "Gintama",
        "Baka to test",
        "Detective Conan/Case Closed",
      ],
      answer: ["Gintama", 2],
    },
    {
      id: 47,
      image: null,
      gif: null,
      question: "Squealer/Yakomaru is the leader of which colony/group?",
      options: ["Giant Hornet", "Robber Fly", "Ground Spider", "Goat Moth"],
      answer: ["Robber Fly", 2],
    },
    {
      id: 48,
      image: null,
      gif: null,
      question:
        "Which of the following 'world lines' was not mentioned in the anime \"Steins;Gate\"?",
      options: [
        "The α world line (alpha)",
        "The ß world line (beta)",
        "The X world line (lambda)",
        "The Steins;Gate world line",
      ],
      answer: ["The X world line (lambda)", 3],
    },
    {
      id: 49,
      image: null,
      gif: null,
      question: "Who voiced Touka Kirishima in the Tokyo Ghoul Dub?",
      options: [
        "Cherami Leigh",
        "Brina Palencia",
        "Caitlin Glass",
        "Kate Higgins",
      ],
      answer: ["Brina Palencia", 2],
    },
    {
      id: 50,
      image: null,
      gif: null,
      question: "Which shinigami dropped his notebook in the human world?",
      options: ["Grell Sutcliff", "Rem", "Asuna", "Ryuk"],
      answer: ["Ryuk", 4],
    },
    {
      id: 51,
      image: null,
      gif: null,
      question:
        'From which anime is the quote "People die when they are killed." ?',
      options: ["Fate/stay Night", "Mobile Suit Gundam", "Steins;Gate", "SAO"],
      answer: ["Fate/stay Night", 1],
    },
    {
      id: 52,
      image: null,
      gif: null,
      question: "Which anime has the OP 'Kyouran Hey Kids!!' ?",
      options: ["Nisekoi", "Noragami", "SAO", "Fairy Tail"],
      answer: ["Noragami", 2],
    },
    {
      id: 53,
      image: null,
      gif: null,
      question: "Yuno Gasai and Yukiteru Amano both feature in which anime?",
      options: ["Corpse Party", "Mirai Nikki", "Death Note", "Steins;Gate"],
      answer: ["Mirai Nikki", 2],
    },
    {
      id: 54,
      image: null,
      gif: null,
      question:
        "What is the name of the organisation who's aim is to exterminate ghouls?",
      options: ["CCG", "SOS Brigade", "Aogiri Tree", "None of the above"],
      answer: ["CCG", 1],
    },
    {
      id: 55,
      image: null,
      gif: null,
      question:
        "In which part of the Black Butler franchise did Arthur appear?",
      options: [
        "Kuroshitsuji",
        "Kuroshitsuji: Book Of Circus",
        "Kuroshitsuji: Book Of Murder",
        "None of the above",
      ],
      answer: ["Kuroshitsuji: Book Of Murder", 3],
    },
    {
      id: 56,
      image: null,
      gif: null,
      question:
        "In Danganronpa: The Animation, which character is executed first?",
      options: [
        "Mukuro Ikusaba",
        "Leon Kuwata",
        "Sayaka Maizono",
        "None of the above",
      ],
      answer: ["Leon Kuwata", 2],
    },
    {
      id: 57,
      image: null,
      gif: "https://c.tenor.com/BXAQ1hjzpKcAAAAC/chitoge-kirisaki-nisekoi.gif",
      question: "Guess this character",
      options: [
        "Kirisaki Chitoge",
        "Kagura",
        "Marika Tachibana",
        "Silvia  Lautreamont",
      ],
      answer: ["Kirisaki Chitoge", 1],
    },
    {
      id: 58,
      image: null,
      gif: "https://c.tenor.com/M0ZS2CZBceIAAAAC/charlotte-anime.gif",
      question: "Guess this character",
      options: ["Asuna Yuuiki", "Alice Nakiri", "Nao Tomori", "Rin Tohsaka"],
      answer: ["Nao Tomori", 3],
    },
    {
      id: 59,
      image: null,
      gif: "https://i.pinimg.com/originals/b0/b2/05/b0b20513410beb0a411af55423e91b16.gif",
      question: "Guess the pinked hair girl",
      options: [
        "Lisesharte Atismata",
        "Airi Arcadia",
        "Celistia Ralgris",
        "Philuffy Aingram",
      ],
      answer: ["Philuffy Aingram", 4],
    },
    {
      id: 60,
      image: null,
      gif: null,
      question:
        "Kaho Hinata and Maika Sakuranomiya both feature in which anime?",
      options: ["Blend-S", "Nisekoi", "Fairy Tail", "One Piece"],
      answer: ["Blend-S", 1],
    },
    {
      id: 61,
      image: null,
      gif: null,
      question:
        "Kirito tries to find a sword as balanced and powerful as his other blade, the Elucidator but quickly finds out that the only way to accomplish this is with rare materials and a highly skilled blacksmith. After questing with Lisbeth, the top level blacksmith he needed, they get the material he needs and together they finish the weapon. This is Kirito's other sword that he uses with his Dual Wielding ability.",
      options: [
        "Black Iron Great Sword",
        "Dark Repulser",
        "Black Lily Sword",
        "Holy Sword Excalibur",
      ],
      answer: ["Dark Repulser", 2],
    },
    {
      id: 62,
      image: null,
      gif: null,
      question:
        "What is the last name of Edward and Alphonse in the Fullmetal Alchemist series.",
      options: ["Eric", "Dragneel", "Sato", "Ishigami"],
      answer: ["Eric", 1],
    },
    {
      id: 63,
      image: null,
      gif: "https://i.kym-cdn.com/photos/images/newsfeed/000/947/643/4c0.gif",
      question: "What is the name of this opening song?",
      options: ["Hope", "Rally Go Round", "Ft.", "Click"],
      answer: ["Rally Go Round", 2],
    },
    {
      id: 64,
      image: null,
      gif: "https://i.makeagif.com/media/10-13-2015/U-ipdx.gif",
      question: "Guess this opening.",
      options: [
        "Ft. (Fairy Tail)",
        "S.O.W. Sense of Wonder (Fairy Tail)",
        "Believe in Myself (Fairy Tail)",
        "Egao No Mahou (Fairy Tail)",
      ],
      answer: ["Egao No Mahou (Fairy Tail)", 4],
    },
    {
      id: 65,
      image: null,
      gif: "https://media0.giphy.com/media/HCgIpUBbHxVX6degal/giphy.gif?cid=790b76119582464d32479e1e29a12f6f8e2eae6464c9da63&rid=giphy.gif&ct=g",
      question:
        "This scene is from the anime 86 (Season 1), what is the episode of this scene?",
      options: ["Episode 4", "Episode 7", "Episode 2", "Episode 1"],
      answer: ["Episode 2", 3],
    },
    {
      id: 66,
      image: null,
      gif: "https://c.tenor.com/1FCh4hBt7a0AAAAC/no-game-no-life-zero-schwi-dola.gif",
      question: "Guess this character.",
      options: [
        "Alice Nakiri",
        "Marika Tachibana",
        "Shuvi Dola",
        "Silvia Lautreamont",
      ],
      answer: ["Shuvi Dola", 3],
    },
    {
      id: 67,
      image: null,
      gif: "https://c.tenor.com/RrS6tFt-tocAAAAC/anime-best-girl.gif",
      question: "Guess this character.",
      options: ["Seishirou Tsugumi", "Lisbeth", "Shinobu", "Makise Kurisu"],
      answer: ["Makise Kurisu", 4],
    },
    {
      id: 68,
      image: null,
      gif: "https://c.tenor.com/PO0q3rINdL8AAAAC/amane-suou-suou.gif",
      question: "Name this character",
      options: [
        "Amane Suou",
        "Lisbeth",
        "Alice Nakiri",
        "Cassandra Lautreamont",
      ],
      answer: ["Amane Suou", 1],
    },
    {
      id: 69,
      image: null,
      gif: "https://c.tenor.com/TBL2c8I16LcAAAAM/isla-plastic-memories.gif",
      question: "Guess this character",
      options: ["Michiru Kinushima", "Isla", "Shinobu", "Marika Tachibana"],
      answer: ["Isla", 2],
    },
    {
      id: 70,
      image: null,
      gif: "https://c.tenor.com/R9ig7PfDAAYAAAAC/anime-food-wars.gif",
      question: "Guess this character",
      options: ["Isla", "Benio Adashino", "Alice Nakiri", "Mine"],
      answer: ["Alice Nakiri", 3],
    },
    {
      id: 71,
      image: null,
      gif: "https://c.tenor.com/mQBuz8ZM8c4AAAAM/michiru-michiru-shocked.gif",
      question: "Guess this character",
      options: ["Amane Suou", "Hina", "Mayura Otomi", "Michiru Matsushima"],
      answer: ["Michiru Matsushima", 4],
    },
    {
      id: 72,
      image: null,
      gif: "https://i.pinimg.com/originals/b0/8c/12/b08c127c83b2d8120d72a43095fbfcd6.gif",
      question: "Guess this character",
      options: ["Rikka Takarada", "Reina Izumi", "Mayuri Otomi", "Mine"],
      answer: ["Rikka Takarada", 1],
    },
    {
      id: 73,
      image: null,
      gif: "https://i.pinimg.com/originals/b6/82/25/b68225630a66d352224ed5c5628421e6.gif",
      question: "Name this character",
      options: ["Kaho Hinata", "Reina Izumi", "Shinobu", "Rio Futaba"],
      answer: ["Reina Izumi", 2],
    },
    {
      id: 74,
      image: null,
      gif: "https://i.pinimg.com/originals/e6/f4/c5/e6f4c55f526873611c24dce05438ee0a.gif",
      question: "Guess this character",
      options: ["Taki", "Shin Nouzen", "Raku Ichijou", "Haruhiko Ichijo"],
      answer: ["Haruhiko Ichijo", 4],
    },
    {
      id: 75,
      image: null,
      gif: "https://c.tenor.com/iZjSGTjKzyQAAAAC/shinei-nouzen-86.gif",
      question: "Guess this character",
      options: ["Shin Nouzen", "Kazuma Sato", "Kazami Yuuji", "Lux Arcadia"],
      answer: ["Shin Nouzen", 1],
    },
    {
      id: 76,
      image: null,
      gif: "https://c.tenor.com/yoWsfQjZmlwAAAAC/wataten-an-angel-flew-down-to-me.gif",
      question: "Name this character",
      options: [
        "Mami Nanami",
        "Miyako Hoshino",
        "Tatenashi Sarashiki",
        "Mai Kawakami",
      ],
      answer: ["Miyako Hoshino", 2],
    },
    {
      id: 77,
      image: null,
      gif: null,
      question:
        "Which anime heavily features music from the genre &quot;Eurobeat&quot;?",
      options: ["Initial D", "Wangan Midnight", "Kino no Tabi", "Cowboy Bebop"],
      answer: ["Initial D", 1],
    },
    {
      id: 78,
      image: null,
      gif: null,
      question:
        'In the anime series "Full Metal Alchemist", what do Alchemists consider the greatest taboo?',
      options: [
        "Transmuting Lead Into Gold",
        "Using Alchemy For Crime ",
        "Human Transmutation",
        "Preforming Without A Permit",
      ],
      answer: ["Human Transmutation ", 3],
    },
    {
      id: 79,
      image: null,
      gif: null,
      question: "In the 9th Pokemon movie, who is the Prince of the Sea?",
      options: ["Ash", "May", "Phantom", "Manaphy"],
      answer: ["Manaphy", 4],
    },
    {
      id: 80,
      image: null,
      gif: null,
      question: 'In "Inuyasha" what are the heros are looking to collect?',
      options: ["Dragon Balls", "Jewel Shards", "Rave Stones", "Sacred Stones"],
      answer: ["Jewel Shards", 2],
    },
    {
      id: 81,
      image: null,
      gif: null,
      question:
        'In "Shakugan no Shana", what was the Shana usually referred as?',
      options: [
        "Flame Haze",
        "Flame-Haired Burning-Eyed Haze",
        "Flame-Haired Burning-Eyed Hunter",
        "Shana",
      ],
      answer: ["Flame-Haired Burning-Eyed Hunter", 3],
    },
    {
      id: 82,
      image: null,
      gif: null,
      question:
        "Which one of these Manga titles was not created by Urasawa Naoki?",
      options: [
        "My Father's Journal",
        "Billy Bat",
        "20th Century Boys",
        "Monster",
      ],
      answer: ["My Father's Journal", 1],
    },
    {
      id: 83,
      image: null,
      gif: null,
      question:
        'Which of the following countries does "JoJo\'s Bizarre Adventure: Stardust Crusaders" not take place in?',
      options: ["India", "Pakistan", "Egypt", "Philippines"],
      answer: ["Philippines", 4],
    },
    {
      id: 84,
      image: null,
      gif: null,
      question:
        'What year was "JoJo\'s Bizarre Adventure: Phantom Blood" first released?',
      options: ["2013", "1987", "1983", "1995"],
      answer: ["1987", 2],
    },
    {
      id: 85,
      image: null,
      gif: null,
      question:
        "The main protagonist of the fifth part of JoJo's Bizarre Adventure is which of the following?",
      options: [
        "Guido Mista",
        "Jonathan Joestar",
        "Giorno Giovanna",
        "Joey JoJo",
      ],
      answer: ["Giorno Giovanna", 3],
    },
    {
      id: 86,
      image: null,
      gif: null,
      question:
        "Which song was the callsign for Stefan Verdemann's KWFM radio station in Urasawa Naoki's \"Monster\"?",
      options: [
        "Over the Rainbow",
        "What a Wonderful World",
        "When You Wish Upon A Star",
        "Singing In The Rain",
      ],
      answer: ["Over the Rainbow", 1],
    },
    {
      id: 87,
      image: null,
      gif: null,
      question:
        "In the anime Assassination Classroom what is the class that Korosensei teaches?",
      options: ["Class 3-A", "Class 3-E", "Class 3-B", "Class 3-D"],
      answer: ["Class 3-E", 2],
    },
    {
      id: 88,
      image: null,
      gif: null,
      question:
        "In the anime Seven Deadly Sins what is the name of one of the sins?",
      options: ["Sakura", "Ayano", "Sheska", "Diane"],
      answer: ["Diane", 4],
    },
    {
      id: 89,
      image: null,
      gif: null,
      question:
        'In "A Certain Scientific Railgun", how many "sisters" did Accelerator have to kill to achieve the rumored level 6?',
      options: ["20,000", "128", "10,000", "5,000"],
      answer: ["20,000", 1],
    },
    {
      id: 90,
      image: null,
      gif: null,
      question:
        'Which animation studio animated the 2016 anime "Mob Psycho 100"?',
      options: ["A-1 Pictures", "Bones", "Shaft", "Madhouse"],
      answer: ["Bones", 2],
    },
    {
      id: 91,
      image: null,
      gif: null,
      question:
        'In the ADV (English) Dub of the anime "Ghost Stories", which character is portrayed as a Pentacostal Christian?',
      options: [
        "Momoko Koigakubo",
        "Hajime Aoyama",
        "Satsuki Miyanoshita",
        "Mio Itai",
      ],
      answer: ["Momoko Koigakubo", 1],
    },
    {
      id: 92,
      image: null,
      gif: null,
      question:
        "What was studio Trigger's first original long-form animated series for television?",
      options: ["Kiznaiver", "Inferno Cop", "Gurren Lagann", "Kill la Kill"],
      answer: ["Kill la Kill", 4],
    },
    {
      id: 93,
      image: null,
      gif: null,
      question:
        'Ikki Kurogane is known by what nickname at the beginning of "Chivalry of a Failed Knight"?',
      options: ["Another One", "Worst One", "Blazer", "Princess"],
      answer: ["Worst One", 2],
    },
    {
      id: 94,
      image: null,
      gif: null,
      question: 'Satella in "Re:Zero" is the witch of what?',
      options: ["Envy", "Pride", "Sloth", "Wrath"],
      answer: ["Envy", 1],
    },
    {
      id: 95,
      image: null,
      gif: null,
      question:
        'In "One Piece", what does "the Pirate King" mean to the captain of the Straw Hat Pirates?',
      options: ["Promise", "Adventure", "Freedom", "Friendship"],
      answer: ["Freedom", 3],
    },
    {
      id: 96,
      image: null,
      gif: null,
      question:
        'Which animation studio produced the anime adaptation of "xxxHolic"?',
      options: ["Sunrise", "Xebec", "Kyoto Animation", "Production I.G"],
      answer: ["Production I.G", 4],
    },
    {
      id: 97,
      image: null,
      gif: null,
      question: 'Which animation studio produced "Log Horizon"?',
      options: ["Satelite", "Sunrise", "Xebec", "Production I.G"],
      answer: ["Satelite", 1],
    },
    {
      id: 98,
      image: null,
      gif: null,
      question:
        'Which Japanese music group was formed to produce theme music for the anime "Guilty Crown"?',
      options: ["Goose house", "Babymetal", "Egoist", "Garnidelia"],
      answer: ["Egoist", 3],
    },
    {
      id: 99,
      image: null,
      gif: null,
      question: "In the Overlord Anime who was Cocytus made by?",
      options: [
        "Peroroncino",
        "Warrior Takemikazuchi",
        "Ulbert Alain Odle",
        "Bukubukuchagama",
      ],
      answer: ["Warrior Takemikazuchi", 2],
    },
    {
      id: 100,
      image: null,
      gif: null,
      question:
        "In Dragon Ball Z, who was the first character to go Super Saiyan 2?",
      options: ["Gohan", "Goku", "Vegeta", "Trunks"],
      answer: ["Gohan", 1],
    },
    {
      id: 101,
      image: null,
      gif: null,
      question: 'Which anime heavily features music from the genre "Eurobeat"?',
      options: ["Wangan Midnight", "Kino no Tabi", "Initial D", "Cowboy Bebop"],
      answer: ["Initial D", 3],
    },
  ],
};
