module.exports = {
  quizzes: [
    {
      id: 1,
      image: null,
      gif: null,
      question: "Who is the Pokemon Anime’s main character?",
      options: ["Misty", "Ash", "Light", "Gary"],
      answer: "Ash",
    },
    {
      id: 2,
      image: null,
      gif: null,
      question: "Sophie is a character from which anime movie?",
      options: [
        "Go! Princess PreCure",
        "Snow White With The Red Hair",
        "Howl's Moving Castle",
        "Sailor Moon",
      ],
      answer: "Howl's Moving Castle",
    },
    {
      id: 3,
      image: null,
      gif: null,
      question:
        "In Dragon Ball Super, Goku is sent to destroy earth. What happened to make him change his ways?",
      options: [
        "He just realised it was quite mean",
        "He bumped his head",
        "He couldn't be bothered in the end",
        "No-one knows",
      ],
      answer: "He bumped his head",
    },
    {
      id: 4,
      image: null,
      gif: null,
      question: "What do you have to do with Pokemon?",
      options: [
        "Snatch 'em all",
        "Fetch 'em all",
        "Catch 'em all",
        "Kill 'em all",
      ],
      answer: "Catch 'em all",
    },
    {
      id: 5,
      image: null,
      gif: null,
      question: "How do you do a Naruto run?",
      options: [
        "Put your head forward and arms back",
        "Put your left foot in, right foot out",
        "You do the hockey cokey and turn around",
        "None of the above",
      ],
      answer: "Put your head forward and arms back",
    },
    {
      id: 6,
      image:
        "https://www.beano.com/wp-content/uploads/legacy/54203_blob.png?w=769.984375&strip=all&quality=76",
      gif: null,
      question: "Who is this chubby baby from Spirited Away?",
      options: ["Buddy", "Boh", "Brian", "Beng"],
      answer: "Boh",
    },
    {
      id: 7,
      image: null,
      gif: null,
      question: "How do you spell anime in Japanese?",
      options: ["私の", "マンガ", "オタク", "アニメ"],
      answer: "アニメ",
    },
    {
      id: 8,
      image:
        "https://www.beano.com/wp-content/uploads/legacy/54207_blob.png?w=769.984375&strip=all&quality=76",
      gif: null,
      question: "Which famous anime movie is this from?",
      options: [
        "Spirited Away",
        "Howl's Moving Castle",
        "My Neighbour Totoro",
        "Kiki's Delivery Service",
      ],
      answer: "My Neighbour Totoro",
    },
    {
      id: 9,
      image: null,
      gif: null,
      question: "Which of these ISN'T a type of Pokemon?",
      options: ["Electric", "Rubber", "Grass", "Fire"],
      answer: "Rubber",
    },
    {
      id: 10,
      image: null,
      gif: null,
      question: "Fill in the blank...Dragon ___ Z",
      options: ["Ball", "Beach", "Film", "Mech"],
      answer: "Ball",
    },
    {
      id: 11,
      image: null,
      gif: null,
      question: "What kind of person is Naruto?",
      options: ["A samurai", "A knight", "A ninja", "A soldier"],
      answer: "A ninja",
    },
    {
      id: 12,
      image:
        "https://www.beano.com/wp-content/uploads/legacy/54212_Catbus.jpg?w=769.984375&strip=all&quality=76",
      gif: null,
      question: "In my Neighbour Totoro, what's unusual about this cat?",
      options: [
        "It likes water",
        "It's vegan",
        "It turns into a plane",
        "It's also a bus",
      ],
      answer: "It's also a bus",
    },
    {
      id: 13,
      image: null,
      gif: null,
      question: "In which anime series is Ash Ketchum the main character?",
      options: [
        "Eyeshield 21",
        "Pokémon",
        "Cowboy Bebop",
        "Super Dimension Fortress Macross",
      ],
      answer: "Pokémon",
    },
    {
      id: 14,
      image: null,
      gif: null,
      question: "Dragon Ball’ was created by whom in 1984?",
      options: [
        "Akira Toriyama",
        "Satoshi Tajiri",
        "Hirohiko Araki",
        "Hayao Miyazaki",
      ],
      answer: "Akira Toriyama",
    },
    {
      id: 15,
      image: null,
      gif: null,
      question: "What is the name of Studio Ghibli’s well-known mascot?",
      options: ["Kiki", "Bakura", "Ponyo", "Totoro"],
      answer: "Totoro",
    },
    {
      id: 16,
      image: null,
      gif: null,
      question: "In ‘Sailor Moon’ the anime character Makoto Kino transforms",
      options: [
        "Sailor Mercury",
        "Sailor Venus",
        "Sailor Jupiter",
        "Sailor Mars",
      ],
      answer: "Sailor Jupiter",
    },
    {
      id: 17,
      image: null,
      gif: null,
      question:
        "In ‘Nurato’, the main character, Naruto Uzumaki, is a host for the powerful Nine-Tales. What creature is the Nine-Tails?",
      options: ["Wolf", "Fox", "Bear", "Cat"],
      answer: "Fox",
    },
    {
      id: 18,
      image: null,
      gif: null,
      question:
        "Yubaba is a witch in which animated film written and directed by Hayao Miyazaki?",
      options: [
        "Spirited Away",
        "Castle in the Sky",
        "Ocean Waves",
        "Pom Poko",
      ],
      answer: "Spirited Away",
    },
    {
      id: 19,
      image: null,
      gif: null,
      question: "Which anime series is set in the world of Amestris?",
      options: ["Naruto", "Fullmetal Alchemist", "Sailor Moon", "Pokemon"],
      answer: "Fullmetal Alchemist",
    },
    {
      id: 20,
      image: null,
      gif: null,
      question:
        "In ‘Howl’s Moving Castle’, Sophie is transformed into an old woman by a witch. How old is Sophie as an old woman?",
      options: ["75 years old", "90 years old", "87 years old", "67 years old"],
      answer: "90 years old",
    },
    {
      id: 21,
      image: null,
      gif: null,
      question:
        "In ‘One Piece’, Monkey D. Luffy originally sets out with the Straw Hat Pirates to become the pirate king on which ship?",
      options: ["Going Merry", "Jolly Roger", "Thousand Sunny", "Ever Darker"],
      answer: "Going Merry",
    },
    {
      id: 22,
      image: null,
      gif: null,
      question:
        "Which planet is also known as the Dragon World in ‘Dragon Ball’?",
      options: ["Earth", "Mars", "Jupiter", "Neptune"],
      answer: "Earth",
    },
    {
      id: 23,
      image: null,
      gif: null,
      question:
        "Which series is set in the dark underworld of Victorian London?",
      options: [
        "Phantomhive",
        "Black Butler",
        "Valkyria Chronicles",
        "Blue Exorcist",
      ],
      answer: "Black Butler",
    },
    {
      id: 24,
      image: null,
      gif: null,
      question:
        "In which anime series are Chief Daisuke Aramaki and Major Motoko Kusanag two of the main characters?",
      options: [
        "Paranoia Agent",
        "Dominion",
        "Ghost in the Shell",
        "Fullmetal Alchemist",
      ],
      answer: "Ghost in the Shell",
    },
    {
      id: 25,
      image: null,
      gif: null,
      question: "Which sport is the focus of ‘Eyeshield 21’?",
      options: ["Baseball", "American Football", "Tennis", "Soccer"],
      answer: "American Football",
    },
    {
      id: 26,
      image: null,
      gif: null,
      question:
        "In ’Cowboy Bebop’ Ein is a genetically engineered dog with human levels of intelligence. Which breed of dog is Ein?",
      options: [
        "Great Dane",
        "Cavalier King Charles Spaniel",
        "Dachshund",
        "Pembrokeshire Welsh Corgi",
      ],
      answer: "Pembrokeshire Welsh Corgi",
    },
    {
      id: 27,
      image: null,
      gif: null,
      question: "Which one of the following series is about time travel?",
      options: ["Steins;Gate", "Darker than Black", "City Hunter", "Devilman"],
      answer: "Devilman",
    },
    {
      id: 28,
      image: null,
      gif: null,
      question:
        "A girl searches for magical objects to fulfill her wish, which is the anime?",
      options: ["One Piece", "Dragon Ball", "Fairy Tail", "Naruto"],
      answer: "Dragon Ball",
    },
    {
      id: 29,
      image: null,
      gif: nul,
      question: "What kind of wizard is Lucy in “Fairy Tail” anime?",
      options: ["Ice Wizard", "Celestial Wizard", "Fire Wizard", "Sky Wizard"],
      answer: "Celestial Wizard",
    },
    {
      id: 30,
      image: null,
      gif: null,
      question:
        "Which of the following characters does the “Gum-Gum Pistol” attack belong to?",
      options: ["Chobits", "Black Butler", "Monkey D.Luffy", "Titan"],
      answer: "Monkey D.Luffy",
    },
    {
      id: 31,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/4Z2ZT6DEm_EORh_tUnAocLiemLxNE876EIejVQVq_AA-1-1024x591.jpg",
      gif: null,
      question:
        "Naruto has different types of modes. Do you know what is the name of this mode?",
      options: [
        "Kuruma Chakra Mode",
        "Six Paths Sage Mode",
        "Tailed Beast Bomb Rasen Shiruken",
        "None of the above",
      ],
      answer: "Six Paths Sage Mode",
    },
    {
      id: 32,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/9b580c3252099d75274ce67f638872db-1024x640.jpg",
      gif: null,
      question: "He is Light Yagami. He is the main character of ….. anime.",
      options: ["One Piece", "Fairy Tail", "Death Note", "Dragon Ball"],
      answer: "Death Note",
    },
    {
      id: 33,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/https-_s3-ap-northeast-1.amazonaws.com_psh-ex-ftnikkei-3937bb4_images_8_8_8_0_20780888-3-eng-GB_Cropped-15579467990511961-1024x576.jpg",
      gif: null,
      question: "What is the anime of this picture?",
      options: [
        "Spirited Away",
        "My Neighbour Totoro",
        "One Piece",
        "Fairy Tail",
      ],
      answer: "Spirited Away",
    },
    {
      id: 34,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/a2deecc48e8922fb89e2c473d0409193e2e478f6r1-1280-720v2_uhq-1024x576.jpg",
      gif: null,
      question: "Who is he?",
      options: ["Nami", "Usopp", "Rorona Zoro", "Nico Robin"],
      answer: "Rorona Zoro",
    },
    {
      id: 35,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/catbusbg_by_nellehfox_dcrfa07-fullview-1024x768.jpg",
      gif: null,
      question: "This cat is one of the cutest characters of …… anime.",
      options: ["SAO", "Naruto", "Spirited Away", "In My Neighbour Totoro"],
      answer: "In My Neighbour Totoro",
    },
    {
      id: 36,
      image:
        "https://www.quizexpo.com/wp-content/uploads/2020/02/top-10-beautiful-cute-ghibli-girls-06-1024x611.jpg",
      gif: null,
      question: "Name this character",
      options: ["Nami", "Sophie", "Kiki", "Haruka"],
      answer: "Sophie",
    },
    {
      id: 37,
      image: null,
      gif: null,
      question:
        "What is the name of the ability that allows Fujinuma Satoru to time travel?",
      options: ["Revival", "Time Leap", "Return By Death", "Dues Ex"],
      answer: "Revival",
    },
    {
      id: 38,
      image: null,
      gif: null,
      question:
        'Which character (Kozu No Honkai) said "being wanted... just feels so good"?',
      options: [
        "Yasuraoka Hanabi",
        "Awaya Mugi",
        "Kanai Narumi",
        "Minagawa Akane",
      ],
      answer: "Minagawa Akane",
    },
    {
      id: 39,
      image: null,
      gif: null,
      question:
        '"The law doesn\'t protect people. People protect the law." From which anime is this quote from?',
      options: [
        "Gyakuten Saiban",
        "Inferno Cop",
        "Psycho-Pass",
        "Wizard Barristers",
      ],
      answer: "Psycho-Pass",
    },
    {
      id: 40,
      image: null,
      gif: null,
      question:
        "According to AnimeNewsNetwork (2015), how much does it cost, approximately, to produce 1 season/13 episodes of an anime?",
      options: [
        "$12 - 20 million",
        "$120000 - 200000",
        "$1200 - 20000",
        "$1.2 - 2 million",
      ],
      answer: "$1.2 - 2 million",
    },
    {
      id: 41,
      image: null,
      gif: null,
      question: "What is the name of Megumin's (Konosuba) pet or familiar?",
      options: ["Kuro", "Chomusuke", "Kuroneko", "Megusuke"],
      answer: "Chomusuke",
    },
    {
      id: 42,
      image: null,
      gif: null,
      question:
        'Which fast food chain advertised throughout the anime"Code Geass"',
      options: ["McDonald's", "Subway", "KFC", "Piza Hut"],
      answer: "Pizza Hut",
    },
    {
      id: 43,
      image: null,
      gif: null,
      question:
        'In a curry cooking competition, which character just heated a bag of pre-made curry... and ate it all herself? (From the anime"Kantai Collection")',
      options: ["Inazuma", "Fubuki", "Shimakaze", "Yuudachi"],
      answer: "Shimakaze",
    },
    {
      id: 44,
      image: null,
      gif: null,
      question: "How tall is Haruyuki Arita?",
      options: ["134 cm", "139 cm", "145 cm", "149 cm"],
      answer: "139 cm",
    },
    {
      id: 45,
      image: null,
      gif: null,
      question:
        "Which country did Nakiri Alice live in, prior to joining Totsuki?",
      options: ["Sweden", "France", "Denmark", "Finland"],
      answer: "Denmark",
    },
    {
      id: 46,
      image: null,
      gif: null,
      question:
        'Which anime has a character called:\n"Jugem-Jugem Poop Throwing Machine Shin-chan\'s Day Before Yesterday Underwear Shin-chan•s Life Balmunk Fezarion Isaac Schneider One Thirds Pure Feeling Two Thirds Worried-Over-A-HangnaiI Feeling Though Betrayal Knows My Name Or Does It? I Know The Unknown The Cuttlefish Tastes Kind Of Different Than It Did Last Time [...] Pepepepepepepepepepepe Runny Diarrhea"?',
      options: [
        "Crayon Shin-Chan",
        "Gintama",
        "Baka to test",
        "Detective Conan/Case Closed",
      ],
      answer: "Gintama",
    },
    {
      id: 47,
      image: null,
      gif: null,
      question: "Squealer/Yakomaru is the leader of which colony/group?",
      options: ["Giant Hornet", "Robber Fly", "Ground Spider", "Goat Moth"],
      answer: "Robber Fly",
    },
    {
      id: 48,
      image: null,
      gif: null,
      question:
        "Which of the following 'world lines' was not mentioned in the anime \"Steins;Gate\"?",
      options: [
        "The α world line (alpha)",
        "The ß world line (beta)",
        "The X world line (lambda)",
        "The Steins;Gate world line",
      ],
      answer: "The X world line (lambda)",
    },
    {
      id: 49,
      image: null,
      gif: null,
      question: "Who voiced Touka Kirishima in the Tokyo Ghoul Dub?",
      options: [
        "Cherami Leigh",
        "Brina Palencia",
        "Caitlin Glass",
        "Kate Higgins",
      ],
      answer: "Brina Palencia",
    },
    {
      id: 50,
      image: null,
      gif: null,
      question: "Which shinigami dropped his notebook in the human world?",
      options: ["Grell Sutcliff", "Rem", "Asuna", "Ryuk"],
      answer: "Ryuk",
    },
    {
      id: 51,
      image: null,
      gif: null,
      question:
        'From which anime is the quote "People die when they are killed." ?',
      options: ["Fate/stay Night", "Mobile Suit Gundam", "Steins;Gate", "SAO"],
      answer: "Fate/stay Night",
    },
    {
      id: 52,
      image: null,
      gif: null,
      question: "Which anime has the OP 'Kyouran Hey Kids!!' ?",
      options: ["Nisekoi", "Noragami", "SAO", "Fairy Tail"],
      answer: "Noragami",
    },
    {
      id: 53,
      image: null,
      gif: null,
      question: "Yuno Gasai and Yukiteru Amano both feature in which anime?",
      options: ["Corpse Party", "Mirai Nikki", "Death Note", "Steins;Gate"],
      answer: "Mirai Nikki",
    },
    {
      id: 54,
      image: null,
      gif: null,
      question:
        "What is the name of the organisation who's aim is to exterminate ghouls?",
      options: ["CCG", "SOS Brigade", "Aogiri Tree", "None of the above"],
      answer: "CCG",
    },
    {
      id: 55,
      image: null,
      gif: null,
      question:
        "In which part of the Black Butler franchise did Arthur appear?",
      options: [
        "Kuroshitsuji",
        "Kuroshitsuji: Book Of Circus",
        "Kuroshitsuji: Book Of Murder",
        "None of the above",
      ],
      answer: "Kuroshitsuji: Book Of Murder",
    },
    {
      id: 56,
      image: null,
      gif: null,
      question:
        "In Danganronpa: The Animation, which character is executed first?",
      options: [
        "Mukuro Ikusaba",
        "Leon Kuwata",
        "Sayaka Maizono",
        "None of the above",
      ],
      answer: "Leon Kuwata",
    },
  ],
};
